version: '3.9'
services:
  tsc-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./work:/usr/src/app # ローカルをコンテナ内にマウント
    # command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true 
    