version: '3.9'
services:
  rails-app:
    build:
      context: .
      dockerfile: ./Ruby/Dockerfile
    volumes:
      - ./work:/usr/src/app # ローカルをコンテナ内にマウント
    # command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true 
  sqlite3-db:
    build:
      context: .
      dockerfile: ./sqlite3/Dockerfile
    volumes:
      - ./sqlite3/db:/db
    ports:
      - "5432:5432"
    stdin_open: true
    